version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      #- /home/projects/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: on-failure

volumes:
  prometheus-data:
